usn_newsletter_subscribe:
    pattern:  /newsletter/subscribe
    defaults: { _controller: UsnNewsletterBundle:Default:subscribe }

usn_newsletter_complete:
    pattern:  /newsletter/complete
    defaults: { _controller: UsnNewsletterBundle:Default:complete }

usn_newsletter_unsubscribe:
    path:     /newsletter/unsubscribe/{access_key}
    defaults: { _controller: UsnNewsletterBundle:Default:unsubscribe }

usn_newsletter_unsubscribe_complete:
    path:     /newsletter/unsubscribe_complete/{access_key}
    defaults: { _controller: UsnNewsletterBundle:Default:unsubscribeComplete }
